In [1]:
import pandas as pd

# Series

In [2]:
data = [1, 2, 3, 4, 5]

In [3]:
s = pd.Series(data)

In [4]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
index = ['Linha' + str(i) for i in range (5)]

In [8]:
index

['Linha0', 'Linha1', 'Linha2', 'Linha3', 'Linha4']

In [9]:
s = pd.Series(data = data, index = index)

In [10]:
s

Linha0    1
Linha1    2
Linha2    3
Linha3    4
Linha4    5
dtype: int64

In [11]:
data = {'Linha' + str(i) : i + 1 for i in range(5)}

In [13]:
data

{'Linha0': 1, 'Linha1': 2, 'Linha2': 3, 'Linha3': 4, 'Linha4': 5}

In [12]:
s = pd.Series(data)

In [14]:
s1 = s + 2

In [15]:
s1

Linha0    3
Linha1    4
Linha2    5
Linha3    6
Linha4    7
dtype: int64

In [16]:
s2 =  s + s1

In [17]:
s2

Linha0     4
Linha1     6
Linha2     8
Linha3    10
Linha4    12
dtype: int64

# DataFrame

In [18]:
data = [[1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]]

In [19]:
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
df1 = pd.DataFrame(data = data)

In [21]:
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [22]:
index = ['Linha' + str(i) for i in range(3)]

In [23]:
index

['Linha0', 'Linha1', 'Linha2']

In [24]:
df1 = pd.DataFrame(data = data, index = index)

In [25]:
df1

        0  1  2
Linha0  1  2  3
Linha1  4  5  6
Linha2  7  8  9

In [28]:
columns = ['Coluna' + str(i) for i in range(3)]
columns

['Coluna0', 'Coluna1', 'Coluna2']

In [29]:
df1 = pd.DataFrame(data = data, index = index, columns = columns)

In [30]:
df1

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [31]:
data = {'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
        'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
        'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}

In [32]:
df2 = pd.DataFrame(data)

In [33]:
df2

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [34]:
data = [(1, 2, 3), 
        (4, 5, 6), 
        (7, 8, 9)]

In [35]:
data

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [37]:
df3 = pd.DataFrame(data = data, index = index, columns = columns)
df3

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [38]:
df1[df1 > 0] = 'A'
df1

       Coluna0 Coluna1 Coluna2
Linha0       A       A       A
Linha1       A       A       A
Linha2       A       A       A

In [39]:
df2[df2 > 0] = 'B'
df2

       Coluna0 Coluna1 Coluna2
Linha0       B       B       B
Linha1       B       B       B
Linha2       B       B       B

In [41]:
df3[df3 > 0] = 'C'
df3

       Coluna0 Coluna1 Coluna2
Linha0       C       C       C
Linha1       C       C       C
Linha2       C       C       C

In [42]:
df4 = pd.concat([df1, df2, df3])
df4

       Coluna0 Coluna1 Coluna2
Linha0       A       A       A
Linha1       A       A       A
Linha2       A       A       A
Linha0       B       B       B
Linha1       B       B       B
Linha2       B       B       B
Linha0       C       C       C
Linha1       C       C       C
Linha2       C       C       C

In [43]:
df4 = pd.concat([df1, df2, df3], axis = 1)
df4

       Coluna0 Coluna1 Coluna2 Coluna0 Coluna1 Coluna2 Coluna0 Coluna1 Coluna2
Linha0       A       A       A       B       B       B       C       C       C
Linha1       A       A       A       B       B       B       C       C       C
Linha2       A       A       A       B       B       B       C       C       C